/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as GiftingIndexRouteImport } from './routes/gifting.index'
import { Route as GiftingCorporateRouteImport } from './routes/gifting.corporate'
import { Route as GiftingFestiveRouteImport } from './routes/gifting.festive'
import { Route as GiftingWeddingRouteImport } from './routes/gifting.wedding'
import { Route as HelpFaqsRouteImport } from './routes/help.faqs'
import { Route as HelpPrivacyRouteImport } from './routes/help.privacy'
import { Route as HelpReturnsRouteImport } from './routes/help.returns'
import { Route as HelpShippingRouteImport } from './routes/help.shipping'
import { Route as HelpTermsRouteImport } from './routes/help.terms'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingIndexRoute = GiftingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GiftingRoute,
} as any)
const GiftingCorporateRoute = GiftingCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => GiftingRoute,
} as any)
const GiftingFestiveRoute = GiftingFestiveRouteImport.update({
  id: '/festive',
  path: '/festive',
  getParentRoute: () => GiftingRoute,
} as any)
const GiftingWeddingRoute = GiftingWeddingRouteImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => GiftingRoute,
} as any)
const HelpFaqsRoute = HelpFaqsRouteImport.update({
  id: '/help/faqs',
  path: '/help/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpPrivacyRoute = HelpPrivacyRouteImport.update({
  id: '/help/privacy',
  path: '/help/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpReturnsRoute = HelpReturnsRouteImport.update({
  id: '/help/returns',
  path: '/help/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpShippingRoute = HelpShippingRouteImport.update({
  id: '/help/shipping',
  path: '/help/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTermsRoute = HelpTermsRouteImport.update({
  id: '/help/terms',
  path: '/help/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gifting': typeof GiftingRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/gifting/corporate': typeof GiftingCorporateRoute
  '/gifting/festive': typeof GiftingFestiveRoute
  '/gifting/wedding': typeof GiftingWeddingRoute
  '/help/faqs': typeof HelpFaqsRoute
  '/help/privacy': typeof HelpPrivacyRoute
  '/help/returns': typeof HelpReturnsRoute
  '/help/shipping': typeof HelpShippingRoute
  '/help/terms': typeof HelpTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/gifting/': typeof GiftingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/gifting/corporate': typeof GiftingCorporateRoute
  '/gifting/festive': typeof GiftingFestiveRoute
  '/gifting/wedding': typeof GiftingWeddingRoute
  '/help/faqs': typeof HelpFaqsRoute
  '/help/privacy': typeof HelpPrivacyRoute
  '/help/returns': typeof HelpReturnsRoute
  '/help/shipping': typeof HelpShippingRoute
  '/help/terms': typeof HelpTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/gifting': typeof GiftingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gifting': typeof GiftingRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/gifting/corporate': typeof GiftingCorporateRoute
  '/gifting/festive': typeof GiftingFestiveRoute
  '/gifting/wedding': typeof GiftingWeddingRoute
  '/help/faqs': typeof HelpFaqsRoute
  '/help/privacy': typeof HelpPrivacyRoute
  '/help/returns': typeof HelpReturnsRoute
  '/help/shipping': typeof HelpShippingRoute
  '/help/terms': typeof HelpTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/gifting/': typeof GiftingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/gifting'
    | '/our-story'
    | '/search'
    | '/shop'
    | '/collections/$slug'
    | '/gifting/corporate'
    | '/gifting/festive'
    | '/gifting/wedding'
    | '/help/faqs'
    | '/help/privacy'
    | '/help/returns'
    | '/help/shipping'
    | '/help/terms'
    | '/product/$slug'
    | '/gifting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/our-story'
    | '/search'
    | '/shop'
    | '/collections/$slug'
    | '/gifting/corporate'
    | '/gifting/festive'
    | '/gifting/wedding'
    | '/help/faqs'
    | '/help/privacy'
    | '/help/returns'
    | '/help/shipping'
    | '/help/terms'
    | '/product/$slug'
    | '/gifting'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/gifting'
    | '/our-story'
    | '/search'
    | '/shop'
    | '/collections/$slug'
    | '/gifting/corporate'
    | '/gifting/festive'
    | '/gifting/wedding'
    | '/help/faqs'
    | '/help/privacy'
    | '/help/returns'
    | '/help/shipping'
    | '/help/terms'
    | '/product/$slug'
    | '/gifting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  GiftingRoute: typeof GiftingRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  HelpFaqsRoute: typeof HelpFaqsRoute
  HelpPrivacyRoute: typeof HelpPrivacyRoute
  HelpReturnsRoute: typeof HelpReturnsRoute
  HelpShippingRoute: typeof HelpShippingRoute
  HelpTermsRoute: typeof HelpTermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting/': {
      id: '/gifting/'
      path: '/'
      fullPath: '/gifting/'
      preLoaderRoute: typeof GiftingIndexRouteImport
      parentRoute: typeof GiftingRoute
    }
    '/gifting/corporate': {
      id: '/gifting/corporate'
      path: '/corporate'
      fullPath: '/gifting/corporate'
      preLoaderRoute: typeof GiftingCorporateRouteImport
      parentRoute: typeof GiftingRoute
    }
    '/gifting/festive': {
      id: '/gifting/festive'
      path: '/festive'
      fullPath: '/gifting/festive'
      preLoaderRoute: typeof GiftingFestiveRouteImport
      parentRoute: typeof GiftingRoute
    }
    '/gifting/wedding': {
      id: '/gifting/wedding'
      path: '/wedding'
      fullPath: '/gifting/wedding'
      preLoaderRoute: typeof GiftingWeddingRouteImport
      parentRoute: typeof GiftingRoute
    }
    '/help/faqs': {
      id: '/help/faqs'
      path: '/help/faqs'
      fullPath: '/help/faqs'
      preLoaderRoute: typeof HelpFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/privacy': {
      id: '/help/privacy'
      path: '/help/privacy'
      fullPath: '/help/privacy'
      preLoaderRoute: typeof HelpPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/returns': {
      id: '/help/returns'
      path: '/help/returns'
      fullPath: '/help/returns'
      preLoaderRoute: typeof HelpReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/shipping': {
      id: '/help/shipping'
      path: '/help/shipping'
      fullPath: '/help/shipping'
      preLoaderRoute: typeof HelpShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/terms': {
      id: '/help/terms'
      path: '/help/terms'
      fullPath: '/help/terms'
      preLoaderRoute: typeof HelpTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GiftingRouteChildren {
  GiftingCorporateRoute: typeof GiftingCorporateRoute
  GiftingFestiveRoute: typeof GiftingFestiveRoute
  GiftingWeddingRoute: typeof GiftingWeddingRoute
  GiftingIndexRoute: typeof GiftingIndexRoute
}

const GiftingRouteChildren: GiftingRouteChildren = {
  GiftingCorporateRoute: GiftingCorporateRoute,
  GiftingFestiveRoute: GiftingFestiveRoute,
  GiftingWeddingRoute: GiftingWeddingRoute,
  GiftingIndexRoute: GiftingIndexRoute,
}

const GiftingRouteWithChildren =
  GiftingRoute._addFileChildren(GiftingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  GiftingRoute: GiftingRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  HelpFaqsRoute: HelpFaqsRoute,
  HelpPrivacyRoute: HelpPrivacyRoute,
  HelpReturnsRoute: HelpReturnsRoute,
  HelpShippingRoute: HelpShippingRoute,
  HelpTermsRoute: HelpTermsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
